[development]
address = "127.0.0.1"
port = 8080
workers = 4
keep_alive = 5
log = "debug"

[development.databases.postgres_db]
url = "postgres://root:pass@127.0.0.1/blog"


[production]
adress = "0.0.0.0"
port = 8000
workers = 4
keep_alive = 5
log = "normal"
