---
# Generation of Kubernetes YAML is still under development!
#
# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-1.4.4
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2019-08-25T11:33:59Z"
  labels:
    app: pg_dev
  name: pg_dev
spec:
  containers:
    - command:
        - /entrypoint.sh
      env:
        - name: PATH
          value: /usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        - name: TERM
          value: xterm
        - name: HOSTNAME
        - name: container
          value: podman
        - name: PYTHON_VERSION
          value: 3.7.3
        - name: PYTHONPATH
          value: /pgadmin4
        - name: PGADMIN_DEFAULT_EMAIL
          value: ${PGADMIN_DEFAULT_EMAIL}
        - name: PYTHON_PIP_VERSION
          value: 19.1.1
        - name: PGADMIN_DEFAULT_PASSWORD
          value: ${PGADMIN_DEFAULT_PASSWORD}
        - name: LANG
          value: C.UTF-8
      image: docker.io/dpage/pgadmin4:4.12
      name: pgadmin
      ports:
        - containerPort: 80
          hostPort: 5050
          protocol: TCP
      resources: {}
      securityContext:
        allowPrivilegeEscalation: true
        capabilities: {}
        privileged: false
        readOnlyRootFilesystem: false
      workingDir: /pgadmin4
    - command:
        - docker-entrypoint.sh
        - postgres
      env:
        - name: PATH
          value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/postgresql/11/bin
        - name: TERM
          value: xterm
        - name: HOSTNAME
        - name: container
          value: podman
        - name: PGDATA
          value: /var/lib/postgresql/data
        - name: POSTGRES_DB
          value: shep
        - name: POSTGRES_PASSWORD
          value: ${POSTGRES_PASSWORD}
        - name: GOSU_VERSION
          value: "1.11"
        - name: PG_MAJOR
          value: "11"
        - name: PG_VERSION
          value: 11.5-1.pgdg90+1
        - name: LANG
          value: en_US.utf8
        - name: POSTGRES_USER
          value: ${POSTGRES_USER}
      image: docker.io/library/postgres:12.2
      name: postgres
      ports:
        - containerPort: 5432
          hostPort: 5432
          protocol: TCP
      resources: {}
      securityContext:
        allowPrivilegeEscalation: true
        capabilities: {}
        privileged: false
        readOnlyRootFilesystem: false
      workingDir: /
status: {}
